"""Snapshot per-hero global stat averages from deadlock-api.com into data/baselines.js.

Mastery points are scored relative to these averages, so an average game on any
hero is worth the same. The snapshot is frozen on purpose: re-run this only when
you want to rebalance (e.g. after a big patch), not on every page load.

    python tools/build_baselines.py [--days 90]
"""
import argparse, json, time, urllib.request, urllib.parse, pathlib, datetime

API = "https://api.deadlock-api.com"
STATS = ["kills", "assists", "player_damage", "player_healing", "boss_damage",
         "net_worth", "last_hits", "denies"]
MODES = {"normal": "normal", "brawl": "street_brawl"}


def get(path, **params):
    url = f"{API}{path}?{urllib.parse.urlencode(params)}"
    for attempt in range(4):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "dead-ledger/0.1"})
            with urllib.request.urlopen(req, timeout=120) as r:
                return json.load(r)
        except Exception as e:  # rate limit / transient
            print(f"  retry {attempt + 1} {path}: {e}")
            time.sleep(5 * (attempt + 1))
    raise RuntimeError(url)


def summarize(metrics):
    out = {}
    for s in STATS:
        m = metrics.get(s)
        if m:
            out[s] = {"avg": round(m["avg"], 2), "p50": round(m["percentile50"], 2),
                      "p90": round(m["percentile90"], 2)}
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--days", type=int, default=90)
    args = ap.parse_args()
    since = int(time.time()) - args.days * 86400

    heroes = get("/v1/assets/heroes")
    playable = [h for h in heroes if h.get("player_selectable") and not h.get("disabled")]
    print(f"{len(playable)} playable heroes")

    data = {"generated": datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%d"),
            "window_days": args.days, "modes": {}}
    for key, mode in MODES.items():
        print(f"== {mode}")
        block = {"all": summarize(get("/v1/analytics/player-stats/metrics",
                                      game_mode=mode, min_unix_timestamp=since))}
        for h in playable:
            m = get("/v1/analytics/player-stats/metrics", hero_ids=h["id"],
                    game_mode=mode, min_unix_timestamp=since)
            if m and m.get("kills"):
                block[str(h["id"])] = summarize(m)
            print(f"  {h['name']:<14} {'ok' if str(h['id']) in block else 'no data'}")
            time.sleep(0.35)
        data["modes"][key] = block

    out = pathlib.Path(__file__).resolve().parent.parent / "public" / "data" / "baselines.js"
    out.write_text("// Generated by tools/build_baselines.py - do not edit by hand.\n"
                   f"globalThis.DM_BASELINES = {json.dumps(data, separators=(',', ':'))};\n",
                   encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
