"""Snapshot the static game assets the site needs into data/assets.js.

The raw /v1/assets/items payload is ~6MB, far too heavy for every page load, so this
keeps only names, icons and slots: shop items, hero ability icons, rank badges and
accolade names. Re-run after a patch adds items or heroes.

    python tools/build_assets.py
"""
import datetime, json, pathlib, re, urllib.request

API = "https://api.deadlock-api.com"


def get(path):
    req = urllib.request.Request(API + path, headers={"User-Agent": "deadlock-mastery/0.1"})
    with urllib.request.urlopen(req, timeout=120) as r:
        return json.load(r)


def strip_html(s):
    return re.sub(r"\s+", " ", re.sub(r"<[^>]+>", "", s or "")).strip()


def main():
    items = get("/v1/assets/items")
    heroes = [h for h in get("/v1/assets/heroes") if h.get("player_selectable") and not h.get("disabled")]
    ranks = get("/v1/assets/ranks")
    accolades = get("/v1/assets/accolades")

    shop = {}
    for i in items:
        if i.get("type") != "upgrade":
            continue
        img = i.get("shop_image_webp") or i.get("shop_image") or i.get("image_webp") or i.get("image")
        shop[i["id"]] = [i.get("name"), img, i.get("item_slot_type"), int(i.get("item_tier") or 0),
                         int(i.get("cost") or 0), 1 if i.get("shopable") else 0]

    by_class = {i.get("class_name"): i for i in items if i.get("type") == "ability"}
    abilities, kits = {}, {}
    for h in heroes:
        kit = []
        for slot in ("signature1", "signature2", "signature3", "signature4"):
            cls = (h.get("items") or {}).get(slot)
            a = by_class.get(cls)
            if not a:
                continue
            desc = a.get("description") or {}
            if isinstance(desc, str):
                desc = {"desc": desc}
            abilities[cls] = [a.get("id"), a.get("name"), a.get("image_webp") or a.get("image"),
                              strip_html(desc.get("quip") or ""), strip_html(desc.get("desc") or "")]
            kit.append(cls)
        kits[str(h["id"])] = kit

    rank_list = []
    for r in ranks:
        im = r.get("images") or {}
        rank_list.append({"tier": r["tier"], "name": r["name"], "color": r.get("color"),
                          "img": im.get("large_webp") or im.get("large"),
                          "sub": {str(n): im.get(f"small_subrank{n}_webp") or im.get(f"small_subrank{n}") for n in range(1, 7)
                                  if im.get(f"small_subrank{n}")}})

    acc = {str(a["id"]): [a.get("flavor_name"), a.get("class_name")] for a in accolades}

    data = {"generated": datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%d"),
            "items": shop, "abilities": abilities, "kits": kits, "ranks": rank_list, "accolades": acc}
    out = pathlib.Path(__file__).resolve().parent.parent / "data" / "assets.js"
    out.write_text("// Generated by tools/build_assets.py - do not edit by hand.\n"
                   f"window.DM_ASSETS = {json.dumps(data, separators=(',', ':'), ensure_ascii=False)};\n",
                   encoding="utf-8")
    print(f"wrote {out} ({out.stat().st_size // 1024} KB): {len(shop)} items, {len(abilities)} abilities, "
          f"{len(rank_list)} ranks, {len(acc)} accolades")


if __name__ == "__main__":
    main()
